
ADDINHANDLES struct
	hWnd			HWND ?				;Handle of main window
	hClient			HWND ?
	hREd			HWND ?
	hTab			HWND ?
	hBtn			HWND ?
	hFind			HWND ?
	hTbr			HWND ?
	hShp			HWND ?
	hStc			HWND ?
	hCbo			HWND ?
	hCCLB			HWND ?
	hCCTT			HWND ?
	hRes			HWND ?
	hResEd			HWND ?
	hOut			HWND ?
	hImmOut			HWND ?
	hTabOut			HWND ?
	hBrowse			HWND ?
	hProperty		HWND ?
	hSbr			HWND ?
	hDbgReg			HWND ?
	hDbgWatch		HWND ?
	hTabDbg			HWND ?
	hDbgTip			HWND ?
	hInstance		HINSTANCE ?
	hAccel			HACCEL ?
	hMnu			HMENU ?
	hContextMnu		HMENU ?
	hVSplitCur		HCURSOR ?
	hHSplitCur		HCURSOR ?
	hFont			HFONT ?
	hIFont			HFONT ?
	hLnrFont		HFONT ?
	hImlTbr			HIMAGELIST ?
	hImlTbrGray		HIMAGELIST ?
	hMnuIml			HIMAGELIST ?
	hBrBack			HBRUSH ?
	hMenuBrushA		HBRUSH ?
	hMenuBrushB		HBRUSH ?
	hMnuFont		HFONT ?
ADDINHANDLES ends
